name:                abstract-effects
version:             0.1.0.1
github:              "vitalibarozzi/abstract-effects"
license:             MIT
author:              "Joao Vitor Vitali Barozzi"
maintainer:          "vitalivitor@gmail.com"
copyright:           "2023 Joao Vitor Vitali Barozzi"

dependencies:
- base >= 4.7 && < 5
- text
- time
- process

default-extensions:
- MultiParamTypeClasses
- NoImplicitPrelude
- ImplicitParams
- RankNTypes
- ConstraintKinds
- KindSignatures

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wno-redundant-constraints

library:
  source-dirs: src
